# Generated by Django 4.1.5 on 2023-01-15 13:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("display_image", models.CharField(max_length=300, null=True)),
                (
                    "all_image",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300, null=True),
                        size=None,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
