# Generated by Django 4.1.5 on 2023-01-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="description",
            field=models.TextField(),
        ),
    ]
