# Generated by Django 4.1.5 on 2023-01-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("role", models.CharField(max_length=100)),
                ("tagline", models.CharField(max_length=100)),
                ("about", models.TextField()),
                ("description", models.TextField()),
                ("display_image", models.CharField(max_length=300)),
            ],
        ),
    ]
