# Generated by Django 4.1.5 on 2023-02-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
