# Generated by Django 4.1.5 on 2023-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("person", "0002_person_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="skills",
            field=models.ManyToManyField(to="skills.skills"),
        ),
        migrations.AddField(
            model_name="person",
            name="tools",
            field=models.ManyToManyField(to="skills.tools"),
        ),
    ]
