# Generated by Django 4.1.5 on 2023-02-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0003_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=300),
        ),
    ]
